version: '3'
services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3002:3000"
    networks:
      - nuxt-network

networks:
  nuxt-network:
    driver: bridge
